jobs:
  include:
    - os: linux
      dist: xenial
      language: node_js
      node_js: 14
      before_install:
        - sudo apt-get -qq install --no-install-recommends gcc-multilib g++-multilib lzip rpm xvfb
        - sudo apt-get purge -y --auto-remove && sudo rm -rf /var/lib/apt/lists/*
        - sudo apt-get update
        - sudo apt-get install -y --no-install-recommends software-properties-common
        - sudo apt-get -y purge software-properties-common libdbus-glib-1-2 python3-dbus python3-gi python3-pycurl python3-software-properties
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      script:
        - yarn electron-builder --linux --x64
    - os: windows
      language: node_js
      node_js: 14
      script:
        - yarn electron-builder --win --ia32 --x64
    - os: osx
      osx_image: xcode12.5
      language: node_js
      node_js: 14
      script:
        - yarn electron-builder --mac

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_script:
  - npm install -g cross-env
  - git clone https://github.com/Clipteam/clipcc-gui.git ../clipcc-gui --depth=10
  - git clone https://github.com/Clipteam/clipcc-vm.git ../clipcc-vm --depth=10
  - git clone https://github.com/Clipteam/clipcc-block.git ../clipcc-block --depth=10
  - cd ../clipcc-gui
  - yarn --frozen-lockfile && yarn link
  - cross-env NODE_ENV=production yarn run build:dist
  - cd ../clipcc-vm && yarn link
  - cd ../clipcc-block && yarn link
  - cd ../clipcc-desktop
  - yarn link clipcc-gui
  - yarn link clipcc-vm
  - yarn link clipcc-block
  - yarn --frozen-lockfile
  - yarn run fetch
  - cross-env NODE_ENV=production yarn run compile

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/*-*-*-*.zip
    - dist/*-*-*-*.deb
    - dist/*-*-*-*.rpm
    - dist/*-*-*-*.exe
    - dist/*-*-*-*.dmg
    - dist/*-*-*-*.pkg
  on:
    tags: true

notifications:
  webhooks: $WEBHOOK_URL
