name: Build

on:
  workflow_dispatch:

jobs:
  build1:
    name: Build (Linux & Windows)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install dependencies
        run: |
          yarn
          cd node_modules/clipcc-gui
          node gen-meta.js
          cd ../..
      
      - name: Compile
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          NODE_ENV=production yarn run compile
          
      - name: Build
        run: |
          docker run --rm \
            --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
            -v ${PWD}:/project \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine \
            /bin/bash -c "yarn electron-builder --linux --x64 && yarn electron-builder --win --x64 && yarn electron-builder --win --ia32"

      - name: Upload results (linux64)
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: dist/*-linux-x64.zip

      - name: Upload results (win64)
        uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: dist/*-win-x64.zip

      - name: Upload results (win32)
        uses: actions/upload-artifact@v2
        with:
          name: win-ia32
          path: dist/*-win-ia32.zip
